# Build descriptor for flaunch - built with fbuild. So meta.

name: flaunch

repository:
  http://git/flux/flaunch

#
# flaunch Packages we require to run our build
# processes
#
requires: null

# -- Global Properties
props:
  bar: "{username}"
  foo: "{bar}"
  # my_custom_script: |
  #   import platform

  #   class Foo(object):
  #       """ dict that auto-routes based on platform """
  #       def __init__(self, og_dict):
  #           self.__d = og_dict

  #       def __getitem__(self, key):
  #           val = self.__d[key]
  #           if isinstance(val, dict):
  #               return Foo(val.get(platform.system(), val))
  #           return val

  #       def __str__(self):
  #           return str(self.__d)

  #   foo = Foo({
  #       'val1' : 'blarg',
  #       'val2' : { 'foo': 'cool' },
  #       'val3' : { 'Windows' : 'a value under dow', 'Linux' : 'cant touch me' },
  #       'val4' : { 'foo': { 'Windows' : 'testtt', 'Linux' : 'nooo' } }
  #   })

  #   print ()

  #   print (foo['val2'])
  #   print ("-------")
  #   print (foo['val3'])
  #   print ("-------")
  #   print (foo['val4']['foo'])

# -- Package Management
#
# We package these file directly, as in there
# is no intermediate step
#
build:
  type: basic

  #
  # Commands we have to have access to from our current
  # environment. This is useful for when we run custom build
  # utilities
  #
  # local_required:
  #   windows:
  #     - 7z
  #     - msbuild
  #   unix:
  #     - zip
  #     - make

  #
  # Whatever the repo ignores, so should we
  # (this is the default)
  #
  use_gitignore: true

  # pre_build_conditions: --sdpm
  pre_build:
    - ":PRINT {foo}"
    # - ":PRINT {source_dir}"
    # - ":PRINT {source_directory}"
    # - ":PYTHON -f C:/repo/test_me_two.py"
    # - ":PYTHON my_custom_script"
    # - ["--foo",
    #   [ ":PRINT {username} additional commands",
    #     ":PRINT {username} additional asdfasdf"
    #   ]]
    # - windows:
    #     clause:
    #       "\"{username}\" == \"Michael McCartney\""
    #     commands:
    #       - ":PRINT -s -q {homedrive}{homepath} bar cool"
    # - windows:
    #   - ":PRINT OKAY WINDOWS!"


  # post_build:
  #   - :PRINT post build time

  #
  # What to include in our build
  #
  files:
    unix:
      - src
      - flaunch
      - fbuild
      - version.txt
      - endpoints.txt
    windows:
      - src
      - flaunch.bat
      - fbuild.bat
      - version.txt
      - endpoints.txt

  #
  # We just define the launch.json from here
  #
  launch_json:
    executable: "{path}/flaunch"
