# Build descriptor for flaunch - built with fbuild. So meta.

name: flaunch

include:
  - sdpm_package

repositories:
  - https://github.com/StereoD-Development/flaunch
  - http://git/flux/flaunch

#
# flaunch Packages we require to run our build
# processes
#
requires: null

# -- Global Properties
props: null

# -- Package Management
#
# We package these file directly, as in there
# is no intermediate step
#
build:
  type: basic

  #
  # What to include in our build - we include both
  # the windows and linux files to make it agnostic
  # for server-side deployments
  #
  files:
    - src
    - py
    - flaunch.bat
    - flaunch
    - fbuild.bat
    - fbuild
    - fupdate.bat
    - fupdate
    - selfupdate.py
    - version.txt
    - endpoints.txt

  #
  # We just define the launch.json from here
  #
  launch_json:
    executable: "{path}/flaunch"
    env:
      PYTHONPATH: ["{path}"]

# -- The Deployment Proceedure
#
# This changes significantly between setups.
#
deploy:

  branch: master

#
# Section where we can build arbitrary command sequences for
# calling whenever our hearts desire
#
# custom:

#   custom_deploy:

#     commands:
#       - 