# Build descriptor for flaunch - built with fbuild. So meta.

name: flaunch

include:
  - sdpm_package

repositories:
  - https://github.com/StereoD-Development/flaunch
  - http://git/flux/flaunch

#
# flaunch Packages we require to run our build
# processes
#
requires: null

# -- Global Properties
props: null

# -- Package Management
#
# We package these file directly, as in there
# is no intermediate step
#
build:
  type: basic

  #
  # What to include in our build
  #
  files:
    unix:
      - src
      - flaunch
      - fbuild
      - version.txt
      - endpoints.txt
    windows:
      - src
      - win32utils
      - flaunch.bat
      - fbuild.bat
      - version.txt
      - endpoints.txt

  #
  # We just define the launch.json from here
  #
  launch_json:
    executable: "{path}/flaunch"

# -- The Deployment Proceedure
#
# This changes significantly between setups.
#
# deploy:
#   endpoints:
#     - 
