# Build descriptor for flaunch - built with fbuild. So meta.

name: flaunch

include:
  - sdpm_package


# -- Global Properties
props: null

# -- Package Management
build:
  type: basic

  #
  # What to include in our build - we include both
  # the windows and linux files to make it agnostic
  # for server-side deployments
  #
  files:
    - src
    - py
    - flaunch.bat
    - flaunch
    - fbuild.bat
    - fbuild
    - fupdate.bat
    - fupdate
    - selfupdate.py
    - version.txt
    - endpoints.txt

  #
  # We just define the launch.json from here
  #
  launch_json:
    executable: "{path}/flaunch"
    env:
      PYTHONPATH: ["{path}"]


#
# Section where we can build arbitrary command sequences for
# calling whenever our hearts desire
#
raw:

  # run with: fbuilc raw flaunch custom_print_example
  custom_print_example:
    help: "An example of a raw command"
    commands:
      - ":PRINT Example command that does some work with {package} in {source_dir}"

  deploy_pkg_temp:
    help: "Use sdpm version of mcclane to prep for madrid"
    arguments:
      - ["version", "The sdpm version string"]
      - ["fix", "The sdpm hotfix"]
      - ["pkg", "The name of the sdpm package"]
    commands:
      - ":SET /mnt/isilon2/s3d/resources/sw/packages/{pkg}/{version}/{fix} package_base"
      - clause: "'{pkg}' == 'FLUX'"
        commands: ":SET Flux.{version}.{fix}.zip fpack"
      - clause: "'{pkg}' != 'Flux'"
        commands: ":SET {pkg}.{version}.{fix}.zip fpack"
      - ["--windows", ":SET AMD64-Windows arch", ":SET x86_64-Linux arch"]
      - ":CD {package_base}/{arch}"
      - clause: "'{pkg}' == 'flux'"
        commands: ":COPY --force /home/mmccartney/Flux/launch.json ./"
      - ":ZIP ../{fpack} -f ./ -e sdpm.rc -e sdpm.tar.gz -e sdpm.zip -n"
      - ":CD {package_base}"
      - ":COPY --force {fpack} /mnt/vfxbox/_FLUX/flaunch_packages/Flux/{platform}/"
      - ["--winlin", [
          { clause : "'{platform}' == 'Windows'",
            commands : ":COPY --force {fpack} /mnt/vfxbox/_FLUX/flaunch_packages/Flux/Linux/" },
          { clause : "'{platform}' == 'Linux'",
            commands : ":COPY --force {fpack} /mnt/vfxbox/_FLUX/flaunch_packages/Flux/Windows/" }
        ]]
      - ":DEL {fpack}" # Don't need after copy
