# Build descriptor for flaunch - built with fbuild. So meta.

name: flaunch

include:
  - sdpm_package

repositories:
  - https://github.com/StereoD-Development/flaunch
  - http://git/flux/flaunch

#
# flaunch Packages we require to run our build
# processes
#
requires: null

# -- Global Properties
props: null

# -- Package Management
#
# We package these file directly, as in there
# is no intermediate step
#
build:
  type: basic

  #
  # What to include in our build - we include both
  # the windows and linux files to make it agnostic
  # for server-side deployments
  #
  files:
    - src
    - py
    - flaunch.bat
    - flaunch
    - fbuild.bat
    - fbuild
    - fupdate.bat
    - fupdate
    - selfupdate.py
    - version.txt
    - endpoints.txt

  #
  # We just define the launch.json from here
  #
  launch_json:
    executable: "{path}/flaunch"
    env:
      PYTHONPATH: ["{path}"]

# -- The Deployment Proceedure
#
# This changes significantly between setups.
#
deploy:

  branch: master

  #
  # In the event we have a compiled application, we may have the
  # built files installed into a separate location
  #
  compiled_files: "{flux_package_predeploy_folder}/flaunch/{deploy_version}"

  # commands:
  #   -
  #   - ":DEPLOY" # This _must_ be the last command if you want the deployment to go out around the world


#
# Section where we can build arbitrary command sequences for
# calling whenever our hearts desire
#
raw:

  # run with: fbuilc raw flaunch custom_print_example
  custom_print_example:

    help:
      "An example of a raw command"

    commands:
        - ":PRINT Example command that does some work with {package} in {source_dir}"
